py_library(
    name = "planning",
    srcs = [
        "__init__.py",
        "porosity_planner.py",
        "suction_grasp.py",
        "planar_grasp.py"
    ],
    imports = [".."],
    visibility = ["//visibility:public"],
    deps = ["//utils",],
)