py_library(
    name = "robotiq_2f_85",
    srcs = [
        "__init__.py",
        "robotiq_2f_85_constants.py",
        "robotiq_2f_85_control.py",
        "robotiq_2f_85_sim_driver.py",
    ],
    visibility = ["//visibility:public"],
)
