package(
    default_visibility = ["//visibility:public"],
)


py_library(
    name = "utils",
    srcs = [
        "__init__.py",
        "meshcat_utils.py",
        "geometry_utils.py",
    ],
    data = [],
    visibility = ["//visibility:public"],
    deps = [
        "@drake//bindings/pydrake",
    ],
)
