name: Build Piplup
run-name: ${{ github.actor }} is running
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: krishsuresh/piplup
    steps:
      - name: Install librealsense
        run: |
          sudo mkdir -p /etc/apt/keyrings
          curl -sSf https://librealsense.intel.com/Debian/librealsense.pgp | sudo tee /etc/apt/keyrings/librealsense.pgp > /dev/null
          sudo apt-get install apt-transport-https
          echo "deb [signed-by=/etc/apt/keyrings/librealsense.pgp] https://librealsense.intel.com/Debian/apt-repo `lsb_release -cs` main" | \
          sudo tee /etc/apt/sources.list.d/librealsense.list
          sudo apt-get update
          sudo apt-get install librealsense2-dkms
          sudo apt-get install librealsense2-utils
          sudo apt-get install librealsense2-dev
          sudo apt-get install librealsense2-dbg
      - uses: actions/checkout@v4
      - uses: bazelbuild/setup-bazelisk@v3
        with:
          bazelisk-version: v1.18.0
      - name: Mount bazel cache  # Optional
        uses: actions/cache@v4
        with:
          path: "~/.cache/bazel"
          key: bazel
      - run: bazel build //...