name: Build Piplup
run-name: ${{ github.actor }} is running
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: groups
      - run: id
      - name: Setup Drake
        run: ./scripts/setup/install_prereqs.sh
