filegroup(
    name = "models",
    srcs = glob([
        "**/*.sdf",
        "**/*.urdf",
        "**/*.yaml",
        "**/*.xml",
        "**/*.obj",
        "**/*.mtl",
        "**/*.jpg",
        "**/*.png",
    ]),
    visibility = ["//visibility:public"],
)

exports_files(
    glob([
        "**/*.sdf",
        "**/*.urdf",
    ]),
    visibility = ["//visibility:public"],
)
