camera0:
  object_points: 
    - [470, 320]
  background_points:
    - [408,360]
  top_left_coordinate: [340, 220]
  bottom_right_coordinate: [480, 380]

camera1:
  object_points: 
    - [230, 335]
  background_points:
    - [375, 320]
  top_left_coordinate: [0, 0]
  bottom_right_coordinate: [640, 480]

camera2:
  object_points: 
    - [345, 365]
  background_points:
    - [365, 325]
  top_left_coordinate: [0, 0]
  bottom_right_coordinate: [640, 480]

camera3:
  object_points: 
    - [240, 310]
  background_points:
    - [215, 275]
  top_left_coordinate: [0, 0]
  bottom_right_coordinate: [640, 480]

camera4:
  object_points: 
    - [425, 300]
  background_points:
    - [455, 250]
  top_left_coordinate: [0, 0]
  bottom_right_coordinate: [640, 480]
