camera0:
  object_points: 
    - [230, 400]
  background_points:
    - [100, 350]
  top_left_coordinate: [90, 250]
  bottom_right_coordinate: [320, 450]

camera1:
  object_points: 
    - [100, 100]
    - [100, 100]
  background_points:
    - [200, 200]
    - [200, 200]
  top_left_coordinate: [0, 0]
  bottom_right_coordinate: [640, 480]

camera2:
  object_points: 
    - [100, 100]
    - [100, 100]
  background_points:
    - [200, 200]
    - [200, 200]
  top_left_coordinate: [0, 0]
  bottom_right_coordinate: [640, 480]

camera3:
  object_points: 
    - [100, 100]
    - [100, 100]
  background_points:
    - [200, 200]
    - [200, 200]
  top_left_coordinate: [0, 0]
  bottom_right_coordinate: [640, 480]

camera4:
  object_points: 
    - [100, 100]
    - [100, 100]
  background_points:
    - [200, 200]
    - [200, 200]
  top_left_coordinate: [0, 0]
  bottom_right_coordinate: [640, 480]
