camera0:
  object_points: 
    - [400, 315]
  background_points:
    - [390,370]
  top_left_coordinate: [340, 220]
  bottom_right_coordinate: [480, 380]

camera1:
  object_points: 
    - [230, 335]
  background_points:
    - [375, 320]
  top_left_coordinate: [0, 0]
  bottom_right_coordinate: [640, 480]

camera2:
  object_points: 
    - [360, 340]
  background_points:
    - [260, 357]
  top_left_coordinate: [0, 0]
  bottom_right_coordinate: [640, 480]

camera3:
  object_points: 
    - [250, 300]
  background_points:
    - [190, 300]
    - [325, 300]
  top_left_coordinate: [0, 0]
  bottom_right_coordinate: [640, 480]

camera4:
  object_points: 
    - [400, 275]
  background_points:
    - [530, 160]
  top_left_coordinate: [0, 0]
  bottom_right_coordinate: [640, 480]
